core/generator: use db instead of tx for test
The code being tested uses multiple goroutines, but dbtxes can only be
used by one goroutine at a time. To prevent this error, use a test db
instead.

Example error fixed:
```
--- FAIL: TestGetBlocks (0.44s)
reqid=unknown_req_id at=protocol.go:148 t=2016-09-30T07:26:05.18692908Z
error="atsaving snapshot: saving state tree: writing state snapshot to
database: pq: unexpected Parse response 'C'"
```

Closes chain/chainprv#2033